import type { TankCard } from "./types";

export const cards: TankCard[] = [
  {
    id: "t34_76",
    name: "T-34/76",
    nation: "ussr",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText:
      "Средний танк. Генерирует 2 топлива. Может двигаться на диагональные клетки.",
  },
  {
    id: "kv1",
    name: "KV-1",
    nation: "ussr",
    class: "heavy",
    rarity: "uncommon",
    cost: 4,
    attack: 3,
    armor: 2,
    hp: 7,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText:
      "Тяжелый танк. Генерирует 2 топлива. Высокая живучесть, дорогие действия.",
  },
  {
    id: "su76",
    name: "SU-76",
    nation: "ussr",
    class: "td",
    rarity: "common",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText:
      "ПТ-САУ. Генерирует 1 топливо. Атакует только соседние клетки. Не получает ответный урон, если уничтожила цель.",
  },
  {
    id: "panzer_iv",
    name: "Panzer IV",
    nation: "germany",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText:
      "Средний танк. Генерирует 2 топлива. Сбалансированная машина.",
  },
  {
    id: "tiger_i",
    name: "Tiger I",
    nation: "germany",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 5,
    armor: 2,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText:
      "Тяжелый танк. Генерирует 2 топлива. Мощная атака, высокая стоимость действий.",
  },
  {
    id: "stug_iii",
    name: "StuG III",
    nation: "germany",
    class: "td",
    rarity: "uncommon",
    cost: 3,
    attack: 4,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText:
      "ПТ-САУ. Генерирует 1 топливо. Опасна на соседних клетках.",
  },
  {
    id: "m4_sherman",
    name: "M4 Sherman",
    nation: "usa",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 4,
    abilityText:
      "Средний танк. Генерирует 2 топлива. Хорошая инициатива и гибкость.",
  },
  {
    id: "m5_stuart",
    name: "M5 Stuart",
    nation: "usa",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText:
      "Легкий танк. Генерирует 1 топливо. Дешевые действия, быстрое движение и бонус после спавна.",
  },
  {
    id: "churchill",
    name: "Churchill",
    nation: "uk",
    class: "heavy",
    rarity: "uncommon",
    cost: 4,
    attack: 2,
    armor: 3,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText:
      "Тяжелый танк. Генерирует 2 топлива. Очень крепкая броня, но дорогие действия.",
  },
  {
    id: "marder_iii",
    name: "Marder III",
    nation: "germany",
    class: "td",
    rarity: "common",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText:
      "ПТ-САУ. Генерирует 1 топливо. Высокий урон, слабая защита.",
  },
  {
    id: "wespe",
    name: "Wespe",
    nation: "germany",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 3,
    movement: 1,
    fuelGeneration: 1,
    initiative: 1,
    abilityText:
      "САУ. Генерирует 1 топливо. Стреляет далеко и не получает ответный урон при атаке.",
  },
  {
    id: "su_122",
    name: "SU-122",
    nation: "ussr",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 3,
    movement: 1,
    fuelGeneration: 1,
    initiative: 1,
    abilityText:
      "САУ. Генерирует 1 топливо. Дальняя поддержка, дорогая атака.",
  },
  {
    id: "tk_3",
    name: "TK-3",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText: "Танкетка. Дешёвая разведывательная машина для быстрого развёртывания.",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "tks",
    name: "TKS",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText: "Танкетка. Манёвренная машина поддержки с низкой стоимостью действий.",
    onPlayEffects: { hqProtection: 1 },
  },
  {
    id: "tks_20mm",
    name: "TKS 20 mm",
    nation: "poland",
    class: "td",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "ПТ-танкетка. Усиленное 20-мм орудие опасно на соседних клетках.",
  },
  {
    id: "tkf",
    name: "TKF",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 5,
    abilityText: "Танкетка. Улучшенный двигатель помогает снабжению передовых частей.",
  },
  {
    id: "tkw",
    name: "TKW",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText: "Башенная танкетка. Сохраняет мобильность и наносит больше урона.",
  },
  {
    id: "tkd",
    name: "TKD",
    nation: "poland",
    class: "spg",
    rarity: "uncommon",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 2,
    range: 3,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Лёгкая САУ. Может поддерживать наступление дальним огнём.",
  },
  {
    id: "tks_d",
    name: "TKS-D",
    nation: "poland",
    class: "td",
    rarity: "uncommon",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "ПТ-САУ. Мощная, но уязвимая машина ближней противотанковой обороны.",
  },
  {
    id: "tp7_dwuwiezowy",
    name: "7TP dwuwieżowy",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий двухбашенный танк. Универсальная машина ранних польских частей.",
  },
  {
    id: "tp7_jednowiezowy",
    name: "7TP jednowieżowy",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий однобашенный танк. Хорошо сбалансирован для контратак.",
  },
  {
    id: "tp7_wzmocniony",
    name: "7TP wzmocniony",
    nation: "poland",
    class: "light",
    rarity: "rare",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Усиленный лёгкий танк. Развитие 7TP с повышенной живучестью.",
  },
  {
    id: "tp9",
    name: "9TP",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Улучшенный лёгкий танк. Усиливает экономику и сохраняет высокий темп.",
  },
  {
    id: "tp10",
    name: "10TP",
    nation: "poland",
    class: "medium",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Крейсерский танк. Быстрая и сбалансированная машина для манёвренного боя.",
  },
  {
    id: "tp14",
    name: "14TP",
    nation: "poland",
    class: "medium",
    rarity: "rare",
    cost: 4,
    attack: 4,
    armor: 2,
    hp: 6,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText: "Средний танк. Проект усиленной машины для решающей контратаки.",
  },
  {
    id: "vickers_e_type_a",
    name: "Vickers E A",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий двухбашенный танк. Надёжная машина для удержания рубежа.",
  },
  {
    id: "vickers_e_type_b",
    name: "Vickers E B",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 0,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий однобашенный танк. Улучшенное вооружение для борьбы с бронетехникой.",
  },
  {
    id: "renault_ft",
    name: "Renault FT",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 1,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "Лёгкий танк. Устаревший, но доступный резерв оборонительных частей.",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "renault_r35",
    name: "Renault R35",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 2,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "Пехотный танк. Медленная, но хорошо защищённая машина поддержки.",
  },
  {
    id: "hotchkiss_h35",
    name: "Hotchkiss H35",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 2,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Пехотный танк. Компактная бронированная машина для обороны важных позиций.",
  },
  {
    id: "pociag_pancerny_danuta",
    name: "Pociąg pancerny “Danuta”",
    nation: "poland",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 5,
    armor: 3,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 3,
    initiative: 1,
    abilityText: "Бронепоезд. Тяжёлая огневая платформа с высокой живучестью и снабжением.",
  },
  {
    id: "pociag_pancerny_smialy",
    name: "Pociąg pancerny “Śmiały”",
    nation: "poland",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 6,
    armor: 2,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText: "Бронепоезд. Мощная ударная платформа для последнего рубежа обороны.",
  },

  // === 1. Panzer-Division — ранние немецкие машины (Польша 1939) ===

  // Лёгкие танки
  {
    id: "pzkpfw_i_ausf_a",
    name: "Panzer I A",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий танк. Дешёвая разведывательная машина первой волны.",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "pzkpfw_i_ausf_b",
    name: "Panzer I B",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий танк",
    onPlayEffects: { hqProtection: 1 },
  },
  {
    id: "pzkpfw_ii_ausf_c",
    name: "Panzer II C",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий танк. Основная боевая машина 1-й танковой дивизии в Польше.",
  },
  {
    id: "pzkpfw_ii_ausf_f",
    name: "Panzer II F",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий танк. Улучшенное вооружение и немного усиленная броня.",
  },
  {
    id: "pzkpfw_ii_ausf_d",
    name: "Panzer II D",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 3,
    fuelGeneration: 1,
    initiative: 5,
    abilityText: "Быстроходный лёгкий танк. Отличная подвижность для фланговых ударов.",
  },
  {
    id: "panzer_35t",
    name: "Panzer 35(t)",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 3,
    abilityText: "Основной танк",
  },
  {
    id: "panzer_38t",
    name: "Panzer 38(t)",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Чешский лёгкий танк. Любимец немецких экипажей. Отличное сочетание скорости и живучести.",
  },
  {
    id: "pzbef_i",
    name: "Funk Panzer I",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Командирская машина. Улучшает снабжение передовых частей.",
    onPlayEffects: { draw: 1, hqProtection: 1 },
  },

  // Средние танки
  {
    id: "pzkpfw_iii_ausf_a",
    name: "Panzer III A",
    nation: "germany",
    class: "medium",
    rarity: "rare",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText: "Ранний средний танк. 3,7 cm орудие и полноценный 5-членный экипаж.",
  },
  {
    id: "pzkpfw_iii_ausf_d",
    name: "Panzer III D",
    nation: "germany",
    class: "medium",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 2,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText: "Средний танк. Усиленная броня по сравнению с первыми Ausf.",
  },
  {
    id: "pzkpfw_iii_ausf_e",
    name: "Panzer III E",
    nation: "germany",
    class: "medium",
    rarity: "rare",
    cost: 4,
    attack: 4,
    armor: 2,
    hp: 6,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 2,
    abilityText: "Лучшая из ранних «троек». 30-мм лобовая броня.",
  },
  {
    id: "pzkpfw_iv_ausf_a",
    name: "Panzer IV A",
    nation: "germany",
    class: "medium",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 6,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 2,
    abilityText: "Ранний средний танк поддержки. 7,5 cm орудие для борьбы с укреплениями.",
  },
  {
    id: "pzkpfw_iv_ausf_b",
    name: "Panzer IV B",
    nation: "germany",
    class: "medium",
    rarity: "rare",
    cost: 4,
    attack: 4,
    armor: 1,
    hp: 6,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 2,
    abilityText: "Улучшенный Panzer IV. Лучшая трансмиссия и защищённость.",
  },

  // Противотанковые САУ
  {
    id: "panzerjaeger_i",
    name: "PzJäger I",
    nation: "germany",
    class: "td",
    rarity: "uncommon",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Первая немецкая ПТ-САУ. 4,7 cm PaK(t) на шасси Pz I. Опасна в ближнем бою.",
  },
  {
    id: "panzerjaeger_35t",
    name: "PzJäger 35(t)",
    nation: "germany",
    class: "td",
    rarity: "rare",
    cost: 3,
    attack: 5,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "ПТ-САУ на базе чешского 35(t). Мощное орудие, но открытая рубка.",
  },
  {
    id: "panzerjaeger_38t_early",
    name: "PzJäger 38(t) (ранний)",
    nation: "germany",
    class: "td",
    rarity: "rare",
    cost: 3,
    attack: 5,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Опытный истребитель танков на шасси 38(t). Хорошая мобильность и огонь.",
  },

  // Самоходные орудия
  {
    id: "sig_33_pzi",
    name: "Bison I",
    nation: "germany",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 0,
    hp: 3,
    range: 3,
    movement: 1,
    fuelGeneration: 2,
    initiative: 2,
    abilityText: "15 cm тяжёлое пехотное орудие. Мощная поддержка пехоты и укреплений.",
  },
  {
    id: "sig_33_pzii",
    name: "Bison II",
    nation: "germany",
    class: "spg",
    rarity: "rare",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 3,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "Улучшенная версия на шасси «двойки». Лучшая устойчивость при стрельбе.",
  },

  // Тяжёлые / прототипы
  {
    id: "neubaufahrzeug",
    name: "Nb.Fz.",
    nation: "germany",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 5,
    armor: 2,
    hp: 7,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 2,
    abilityText: "Много башенный прототип. 7,5 cm + 3,7 cm. Редчайшая и мощная машина.",
  },
  {
    id: "grosstraktor",
    name: "Großtraktor",
    nation: "germany",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 4,
    armor: 2,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 3,
    initiative: 1,
    abilityText: "Опытный тяжёлый танк 1920–30-х. Огромный, медленный, но крайне редкий.",
  },
  {
    id: "lefh_18_battery",
    name: "leFH 18 Battery",
    nation: "germany",
    class: "spg",
    rarity: "common",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 3,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "artillery",
    supportEffects: {
      hqAttackBonus: 1,
      hqDamageRedirect: 1,
    },
    abilityText:
      "Линия поддержки. Увеличивает атаку штаба на 1 и принимает на себя 1 урон от каждого удара по штабу.",
  },
  {
    id: "opel_blitz_column",
    name: "Opel Blitz Column",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      fuelPerTurn: 1,
      drawEveryTurns: 2,
    },
    abilityText:
      "Линия поддержки. Даёт +1 топливо каждый ход и позволяет добрать дополнительную карту каждый второй ход.",
  },
  {
    id: "sanitaetskraftwagen",
    name: "Sanitaetskraftwagen",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "medical",
    supportEffects: {
      healRandomUnitPerTurn: 1,
    },
    abilityText:
      "Линия поддержки. В начале хода восстанавливает 1 здоровье случайному повреждённому юниту на поле боя.",
  },
];

export function getCard(cardId: string): TankCard {
  const card = cards.find((item) => item.id === cardId);

  if (!card) {
    throw new Error(`Card not found: ${cardId}`);
  }

  return card;
}
