import type { TankCard } from "./types";

export const cards: TankCard[] = [
  {
    id: "t34_76",
    name: "T-34/76",
    nation: "ussr",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText:
      "Средний танк. Генерирует 2 топлива. Может двигаться на диагональные клетки.",
  },
  {
    id: "kv1",
    name: "KV-1",
    nation: "ussr",
    class: "heavy",
    rarity: "uncommon",
    cost: 4,
    attack: 3,
    armor: 2,
    hp: 7,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText:
      "Тяжелый танк. Генерирует 2 топлива. Высокая живучесть. За ход — либо движение, либо атака.",
  },
  {
    id: "su76",
    name: "SU-76",
    nation: "ussr",
    class: "td",
    rarity: "common",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText:
      "ПТ-САУ. Генерирует 1 топливо. Атакует только соседние клетки. Не получает ответный урон, если уничтожила цель.",
  },
  {
    id: "ms_1_t18",
    name: "МС-1",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText:
      "Первый серийный советский танк",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "t26_1931",
    name: "Т-26 1931",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText:
      "Двухбашенный лёгкий танк поддержки пехоты. Доступный ранний резерв.",
  },
  {
    id: "t26_1933",
    name: "Т-26 1933",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText:
      "Однобашенный Т-26 с пушечным вооружением. Простая и надёжная учебная карта.",
  },
  {
    id: "t26_1938",
    name: "Т-26 1938",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText:
      "Поздний Т-26 с конической башней. Крепче ранних учебных машин.",
  },
  {
    id: "bt_2",
    name: "БТ-2",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    combatAbilities: { blitz: true },
    abilityText:
      "Ранний быстроходный танк. Быстро занимает клетки, но плохо держит удар.",
  },
  {
    id: "bt_5",
    name: "БТ-5",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    combatAbilities: { blitz: true },
    abilityText:
      "Быстроходный танк с пушечным вооружением. Хорош для флангового давления.",
  },
  {
    id: "bt_7",
    name: "БТ-7",
    nation: "ussr",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText:
      "Блиц. После выхода на поле может сразу полноценно двигаться и атаковать.",
    combatAbilities: { blitz: true },
  },
  {
    id: "t37a",
    name: "Т-37А",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 2,
    fuelGeneration: 0,
    initiative: 5,
    abilityText:
      "Очень подвижный, но хрупкий",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "t38",
    name: "Т-38",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 1,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText:
      "Разведывательный плавающий танк",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "t40",
    name: "Т-40",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText:
      "Блиц. Поздний малый разведывательный танк быстро развивает наступление.",
    combatAbilities: { blitz: true },
  },
  {
    id: "t24",
    name: "Т-24",
    nation: "ussr",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 2,
    abilityText:
      "",
  },
  {
    id: "t28",
    name: "Т-28",
    nation: "ussr",
    class: "medium",
    rarity: "uncommon",
    cost: 5,
    attack: 3,
    armor: 1,
    hp: 6,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 2,
    abilityText:
      "Многобашенный средний танк",
  },
  {
    id: "t35",
    name: "Т-35",
    nation: "ussr",
    class: "heavy",
    rarity: "rare",
    cost: 6,
    attack: 2,
    armor: 2,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText:
      "Тяжёлый многобашенный танк. За ход — либо движение, либо атака.",
  },
  {
    id: "t46_1",
    name: "Т-46-1",
    nation: "ussr",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText:
      "",
  },
  {
    id: "t-12",
    name: "Т-12",
    nation: "ussr",
    class: "medium",
    rarity: "common",
    cost: 1,
    attack: 2,
    armor: 0,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText:
      "",
  },
  {
    id: "su_5_2",
    name: "СУ-5-2",
    nation: "ussr",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 0,
    hp: 3,
    range: 2,
    movement: 1,
    fuelGeneration: 1,
    initiative: 1,
    abilityText:
      "Ранняя самоходная артиллерия. Держится у края и поддерживает огнём на дистанции.",
  },
  {
    id: "amo_f15",
    name: "АМО Ф15",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      fuelPerTurn: 1,
      hqHealPerTurn: 1,
    },
    abilityText:
      "Даёт +1 топливо и восстанавливает штабу 1 HP в начале хода.",
  },
  {
    id: "ford_aa_ammo",
    name: "Форд-АА",
    nation: "ussr",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      drawEveryTurns: 3,
      healRandomUnitPerTurn: 1,
    },
    abilityText:
      "Лечит 1 повреждённый юнит каждый ход и добирает карту каждый третий ход.",
  },
  {
    id: "gaz_55_ambulance",
    name: "ГАЗ-55",
    nation: "ussr",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 3,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "medical",
    supportEffects: {
      healRandomUnitPerTurn: 2,
      hqHealPerTurn: 1,
    },
    abilityText:
      "В начале хода лечит 2 HP повреждённому юниту и восстанавливает штабу 1 HP.",
  },
  {
    id: "panzer_iv",
    name: "Panzer IV",
    nation: "germany",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 4,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText:
      "Средний танк. Генерирует 2 топлива. Сбалансированная машина.",
  },
  {
    id: "tiger_i",
    name: "Tiger I",
    nation: "germany",
    class: "heavy",
    rarity: "rare",
    cost: 6,
    attack: 5,
    armor: 2,
    hp: 9,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 1,
    abilityText:
      "Тяжелый танк. Генерирует 2 топлива. Мощная атака. За ход — либо движение, либо атака.",
  },
  {
    id: "stug_iii",
    name: "StuG III",
    nation: "germany",
    class: "td",
    rarity: "uncommon",
    cost: 3,
    attack: 4,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText:
      "ПТ-САУ. Генерирует 1 топливо. Опасна на соседних клетках.",
  },
  {
    id: "m4_sherman",
    name: "M4 Sherman",
    nation: "usa",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 3,
    initiative: 4,
    abilityText:
      "Средний танк. Генерирует 2 топлива. Хорошая инициатива и гибкость.",
  },
  {
    id: "m5_stuart",
    name: "M5 Stuart",
    nation: "usa",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText:
      "Блиц. Лёгкий танк быстро входит в бой и после выхода может сразу полноценно действовать.",
    combatAbilities: { blitz: true },
  },
  {
    id: "m1_combat_car",
    name: "M1 Combat Car",
    nation: "usa",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 1,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText:
      "Ранняя кавалерийская машина США. Быстрая разведка с низкой живучестью.",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "m2_light_tank",
    name: "M2 Light Tank",
    nation: "usa",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 5,
    abilityText:
      "Ранний лёгкий танк. Дешёвый вход на поле и высокая подвижность.",
  },
  {
    id: "m2_medium_tank",
    name: "M2 Medium Tank",
    nation: "usa",
    class: "medium",
    rarity: "common",
    cost: 4,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText:
      "Ранний средний танк. Слабее поздних машин, но хорошо поддерживает экономику.",
  },
  {
    id: "m3_stuart",
    name: "M3 Stuart",
    nation: "usa",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 5,
    abilityText:
      "Блиц. Лёгкий танк раннего периода быстро занимает клетки и давит фланги.",
    combatAbilities: { blitz: true },
  },
  {
    id: "m3_lee",
    name: "M3 Lee",
    nation: "usa",
    class: "medium",
    rarity: "uncommon",
    cost: 6,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText:
      "Переходный средний танк. Мощнее учебных машин, но требует больше топлива.",
  },
  {
    id: "m3_halftrack",
    name: "M3 Half-track",
    nation: "usa",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      fuelPerTurn: 2,
      drawEveryTurns: 3,
    },
    abilityText:
      "Полугусеничный транспорт. Даёт +2 топлива и добирает дополнительную карту каждый третий ход.",
  },
  {
    id: "dodge_wc54",
    name: "Dodge WC-54",
    nation: "usa",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "medical",
    supportEffects: {
      healRandomUnitPerTurn: 1,
      drawEveryTurns: 2,
    },
    abilityText:
      "Санитарный автомобиль с мощной логистикой. Лечит 1 повреждённый юнит и добирает карту каждый второй ход.",
  },
  {
    id: "churchill",
    name: "Churchill",
    nation: "uk",
    class: "heavy",
    rarity: "uncommon",
    cost: 4,
    attack: 2,
    armor: 3,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText:
      "Тяжелый танк. Генерирует 2 топлива. Очень крепкая броня. За ход — либо движение, либо атака.",
  },
  {
    id: "marder_iii",
    name: "Marder III",
    nation: "germany",
    class: "td",
    rarity: "common",
    cost: 3,
    attack: 4,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText:
      "ПТ-САУ. Генерирует 1 топливо. Высокий урон, слабая защита.",
  },
  {
    id: "wespe",
    name: "Wespe",
    nation: "germany",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 3,
    movement: 1,
    fuelGeneration: 1,
    initiative: 1,
    abilityText:
      "САУ. Генерирует 1 топливо. Стреляет далеко и не получает ответный урон при атаке.",
  },
  {
    id: "su_122",
    name: "SU-122",
    nation: "ussr",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 3,
    movement: 1,
    fuelGeneration: 0,
    initiative: 1,
    abilityText:
      "САУ. Генерирует 1 топливо. Дальняя поддержка, дорогая атака.",
  },
  {
    id: "tk_3",
    name: "TK-3",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText: "Танкетка. Дешёвая разведывательная машина для быстрого развёртывания.",
    onPlayEffects: { hqProtection: 1 },
  },
  {
    id: "tks",
    name: "TKS",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 5,
    abilityText: "Танкетка. Манёвренная машина поддержки с низкой стоимостью действий.",
    onPlayEffects: { hqProtection: 1 },
  },
  {
    id: "tks_20mm",
    name: "TKS 20 mm",
    nation: "poland",
    class: "td",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "ПТ-танкетка. Усиленное 20-мм орудие опасно на соседних клетках.",
  },
  {
    id: "tkf",
    name: "TKF",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 5,
    abilityText: "Танкетка. Улучшенный двигатель помогает снабжению передовых частей.",
  },
  {
    id: "tkw",
    name: "TKW",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 5,
    abilityText: "Башенная танкетка. Сохраняет мобильность и наносит больше урона.",
  },
  {
    id: "tkd",
    name: "TKD",
    nation: "poland",
    class: "spg",
    rarity: "uncommon",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 2,
    range: 3,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Лёгкая САУ",
  },
  {
    id: "tks_d",
    name: "TKS-D",
    nation: "poland",
    class: "td",
    rarity: "uncommon",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Мощная, но уязвимая машина ближней противотанковой обороны.",
  },
  {
    id: "tp7_dwuwiezowy",
    name: "7TP dwuwieżowy",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 1,
    armor: 0,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Универсальная машина польских частей",
  },
  {
    id: "tp7_jednowiezowy",
    name: "7TP jednowieżowy",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Лёгкий однобашенный танк. Хорошо сбалансирован для контратак.",
  },
  {
    id: "tp7_wzmocniony",
    name: "7TP wzmocniony",
    nation: "poland",
    class: "light",
    rarity: "rare",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 6,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Усиленный лёгкий танк. Развитие 7TP с повышенной живучестью.",
  },
  {
    id: "tp9",
    name: "9TP",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Усиливает экономику и сохраняет высокий темп",
  },
  {
    id: "tp10",
    name: "10TP",
    nation: "poland",
    class: "medium",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 4,
    combatAbilities: { blitz: true },
    abilityText: "Крейсерский танк. Быстрая и сбалансированная машина для манёвренного боя.",
  },
  {
    id: "tp14",
    name: "14TP",
    nation: "poland",
    class: "medium",
    rarity: "rare",
    cost: 4,
    attack: 4,
    armor: 2,
    hp: 6,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 3,
    abilityText: "Средний танк. Проект усиленной машины для решающей контратаки.",
  },
  {
    id: "vickers_e_type_a",
    name: "Vickers E A",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "Лёгкий двухбашенный танк. Надёжная машина для удержания рубежа.",
  },
  {
    id: "vickers_e_type_b",
    name: "Vickers E B",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 0,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 0,
    initiative: 4,
    abilityText: "Лёгкий однобашенный танк. Улучшенное вооружение для борьбы с бронетехникой.",
  },
  {
    id: "renault_ft",
    name: "Renault FT",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 0,
    armor: 1,
    hp: 2,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "Устаревший, но доступный резерв оборонительных частей.",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "renault_r35",
    name: "Renault R35",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 2,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "Пехотный танк. Медленная, но хорошо защищённая машина поддержки.",
  },
  {
    id: "hotchkiss_h35",
    name: "Hotchkiss H35",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 3,
    attack: 3,
    armor: 2,
    hp: 5,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Пехотный танк. Компактная бронированная машина для обороны важных позиций.",
  },
  {
    id: "pociag_pancerny_danuta",
    name: "Pociąg pancerny “Danuta”",
    nation: "poland",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 5,
    armor: 3,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 3,
    initiative: 1,
    abilityText: "Бронепоезд. Тяжёлая огневая платформа с высокой живучестью и снабжением. За ход — либо движение, либо атака.",
  },
  {
    id: "pociag_pancerny_smialy",
    name: "Pociąg pancerny “Śmiały”",
    nation: "poland",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 6,
    armor: 2,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 2,
    initiative: 1,
    abilityText: "Бронепоезд. Мощная ударная платформа для последнего рубежа обороны. За ход — либо движение, либо атака.",
  },

  // === 1. Panzer-Division — ранние немецкие машины (Польша 1939) ===

  // Лёгкие танки
  {
    id: "pzkpfw_i_ausf_a",
    name: "Panzer I A",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 2,
    armor: 0,
    hp: 1,
    range: 1,
    movement: 2,
    fuelGeneration: 0,
    initiative: 4,
    abilityText: "Лёгкий танк",
    onPlayEffects: { draw: 1 },
  },
  {
    id: "pzkpfw_i_ausf_b",
    name: "Panzer I B",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 0,
    initiative: 4,
    abilityText: "Лёгкий танк",
    onPlayEffects: { hqProtection: 1 },
  },
  {
    id: "pzkpfw_ii_ausf_c",
    name: "Panzer II C",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 0,
    initiative: 4,
    abilityText: "Лёгкий танк",
    combatAbilities: { blitz: true },
  },
  {
    id: "pzkpfw_ii_ausf_f",
    name: "Panzer II F",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 4,
    abilityText: "",
  },
  {
    id: "pzkpfw_ii_ausf_d",
    name: "Panzer II D",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 3,
    fuelGeneration: 0,
    initiative: 5,
    combatAbilities: { blitz: true },
    abilityText:
      "",
    
  },
  {
    id: "panzer_35t",
    name: "Panzer 35(t)",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Основной танк",
  },
  {
    id: "panzer_38t",
    name: "Panzer 38(t)",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 4,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 2,
    fuelGeneration: 1,
    initiative: 3,
    abilityText: "Блиц. Отличное сочетание скорости и живучести.",
    combatAbilities: { blitz: true },
  },
  {
    id: "pzbef_i",
    name: "Funk Panzer I",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 4,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    fuelGeneration: 2,
    initiative: 4,
    abilityText: "Улучшает снабжение передовых частей.",
    onPlayEffects: { draw: 1, hqProtection: 1 },
  },

  // Средние танки
  {
    id: "pzkpfw_iii_ausf_a",
    name: "Panzer III A",
    nation: "germany",
    class: "medium",
    rarity: "rare",
    cost: 3,
    attack: 2,
    armor: 1,
    hp: 3,
    range: 1,
    movement: 1,
    fuelGeneration: 0,
    initiative: 3,
    abilityText: "",
  },
  {
    id: "pzkpfw_iii_ausf_d",
    name: "Panzer III D",
    nation: "germany",
    class: "medium",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 2,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 0,
    initiative: 3,
    abilityText: "Средний танк",
  },
  {
    id: "pzkpfw_iii_ausf_e",
    name: "Panzer III E",
    nation: "germany",
    class: "medium",
    rarity: "rare",
    cost: 4,
    attack: 2,
    armor: 2,
    hp: 6,
    range: 1,
    movement: 1,
    fuelGeneration: 0,
    initiative: 2,
    abilityText: "",
  },
  {
    id: "pzkpfw_iv_ausf_a",
    name: "Panzer IV A",
    nation: "germany",
    class: "medium",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "",
  },
  {
    id: "pzkpfw_iv_ausf_b",
    name: "Panzer IV B",
    nation: "germany",
    class: "medium",
    rarity: "rare",
    cost: 5,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 0,
    initiative: 2,
    abilityText: "",
  },

  // Противотанковые САУ
  {
    id: "panzerjaeger_i",
    name: "PzJäger I",
    nation: "germany",
    class: "td",
    rarity: "uncommon",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    fuelGeneration: 0,
    initiative: 3,
    abilityText: "Опасна в ближнем бою.",
  },
  
  {
    id: "panzerjaeger_38t_early",
    name: "Marder III (ранний)",
    nation: "germany",
    class: "td",
    rarity: "rare",
    cost: 3,
    attack: 5,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    fuelGeneration: 0,
    initiative: 3,
    abilityText: "Опытный истребитель танков на шасси 38(t). Хорошая мобильность и огонь.",
  },

  // Самоходные орудия
  {
    id: "sig_33_pzi",
    name: "Bison I",
    nation: "germany",
    class: "spg",
    rarity: "uncommon",
    cost: 4,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 3,
    movement: 1,
    fuelGeneration: 0,
    initiative: 2,
    abilityText: "Мощная поддержка пехоты и укреплений",
  },
  {
    id: "sig_33_pzii",
    name: "Bison II",
    nation: "germany",
    class: "spg",
    rarity: "rare",
    cost: 4,
    attack: 3,
    armor: 1,
    hp: 4,
    range: 3,
    movement: 1,
    fuelGeneration: 1,
    initiative: 2,
    abilityText: "",
  },

  // Тяжёлые / прототипы
  {
    id: "neubaufahrzeug",
    name: "Nb.Fz.",
    nation: "germany",
    class: "heavy",
    rarity: "rare",
    cost: 7,
    attack: 5,
    armor: 2,
    hp: 7,
    range: 1,
    movement: 1,
    fuelGeneration: 0,
    initiative: 2,
    abilityText: "Тяжёлый прототип. За ход — либо движение, либо атака.",
  },
  {
    id: "grosstraktor",
    name: "Großtraktor",
    nation: "germany",
    class: "heavy",
    rarity: "rare",
    cost: 7,
    attack: 4,
    armor: 2,
    hp: 8,
    range: 1,
    movement: 1,
    fuelGeneration: 1,
    initiative: 1,
    abilityText: "Тяжёлый прототип. За ход — либо движение, либо атака.",
  },
  // === Поддержка — Польша 1939 (конкретная техника, а не колонны) ===
  {
    id: "armata_75mm",
    name: "Armata 75 mm",
    nation: "poland",
    class: "spg",
    rarity: "common",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 3,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "artillery",
    supportEffects: {
      hqAttackBonus: 1,
      hqDamageRedirect: 1,
    },
    abilityText: "Увеличивает атаку штаба и принимает часть урона на себя.",
  },
  {
    id: "haubica_100mm",
    name: "Haubica 100 mm",
    nation: "poland",
    class: "spg",
    rarity: "uncommon",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 3,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "artillery",
    supportEffects: {
      hqAttackBonus: 1,
      hqDamageRedirect: 2,
    },
    abilityText: "Чешская 100-мм гаубица. Сильное прикрытие штаба при обороне.",
  },
  {
    id: "ciagacz_c4p",
    name: "Ciągacz C4P",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      fuelPerTurn: 2,
    },
    abilityText: "Польский артиллерийский тягач. Даёт +2 топлива в ход — мощное снабжение.",
  },
  {
    id: "fiat_508_junak",
    name: "Fiat 508 Junak",
    nation: "poland",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      drawEveryTurns: 2,
    },
    abilityText: "Позволяет добирать дополнительную карту каждый второй ход.",
  },
  {
    id: "karetka_sanitarnaya",
    name: "Karetka sanitar",
    nation: "poland",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "medical",
    supportEffects: {
      healRandomUnitPerTurn: 1,
    },
    abilityText: "В начале хода восстанавливает 1 HP случайному повреждённому юниту.",
  },

  // === Поддержка — Германия, ранние (Польша 1939, конкретная техника) ===
  {
    id: "lefh_18",
    name: "leFH 18",
    nation: "germany",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 0,
    armor: 0,
    hp: 3,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "artillery",
    supportEffects: {
      hqAttackBonus: 2,
    },
    abilityText: "Увеличивает атаку штаба на 2",
  },
  {
    id: "leig_18",
    name: "leIG 18",
    nation: "germany",
    class: "spg",
    rarity: "common",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "artillery",
    supportEffects: {
      hqAttackBonus: 1,
    },
    abilityText: "Лёгкая пехотная пушка: +1 к атаке штаба.",
  },
  {
    id: "mercedes_g3a",
    name: "Mercedes G3a",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      fuelPerTurn: 1,
      hqAttackBonus: 1,
    },
    abilityText: "Даёт +1 топливо и помогает штабу вести огонь точнее: +1 к атаке.",
  },
  {
    id: "adler_type_10_n",
    name: "Adler 10N",
    nation: "germany",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "transport",
    supportEffects: {
      drawEveryTurns: 3,
      hqAttackBonus: 1,
    },
    abilityText: "Даёт +1 к атаке штаба и добирает карту каждый третий ход.",
  },
  {
    id: "sanitaetskraftwagen",
    name: "Sanitätskraftwgn",
    nation: "germany",
    class: "light",
    rarity: "uncommon",
    cost: 2,
    attack: 0,
    armor: 0,
    hp: 2,
    range: 0,
    movement: 0,
    fuelGeneration: 0,
    initiative: 1,
    deploymentZone: "support",
    supportRole: "medical",
    supportEffects: {
      healRandomUnitPerTurn: 1,
      hqDamageRedirect: 1,
    },
    abilityText: "В начале хода лечит 1 повреждённый юнит.",
  },
];

const CARD_ID_ALIASES: Record<string, string> = {
  ba_10: "t-12",
  zis_5_supply: "amo_f15",
  gaz_aa_ammo: "ford_aa_ammo",
};

export function normalizeCardId(cardId: string): string | null {
  const resolvedCardId = CARD_ID_ALIASES[cardId] ?? cardId;
  const cardExists = cards.some((item) => item.id === resolvedCardId);

  return cardExists ? resolvedCardId : null;
}

export function getCardOrNull(cardId: string): TankCard | null {
  const resolvedCardId = normalizeCardId(cardId);

  if (!resolvedCardId) return null;

  return cards.find((item) => item.id === resolvedCardId) ?? null;
}

export function getCard(cardId: string): TankCard {
  const card = getCardOrNull(cardId);

  if (!card) {
    throw new Error(`Card not found: ${cardId}`);
  }

  return card;
}
