import type { TankCard } from "./types";

export const cards: TankCard[] = [
  {
    id: "t34_76",
    name: "T-34/76",
    nation: "ussr",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    initiative: 3,
    abilityText: "Универсальный средний танк.",
  },
  {
    id: "kv1",
    name: "KV-1",
    nation: "ussr",
    class: "heavy",
    rarity: "uncommon",
    cost: 4,
    attack: 3,
    armor: 2,
    hp: 7,
    range: 1,
    movement: 1,
    initiative: 1,
    abilityText: "Тяжелая броня.",
  },
  {
    id: "su76",
    name: "SU-76",
    nation: "ussr",
    class: "td",
    rarity: "common",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 1,
    initiative: 2,
    abilityText: "ПТ-САУ: высокая дальность и урон.",
  },
  {
    id: "panzer_iv",
    name: "Panzer IV",
    nation: "germany",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    initiative: 3,
    abilityText: "Надежный средний танк.",
  },
  {
    id: "tiger_i",
    name: "Tiger I",
    nation: "germany",
    class: "heavy",
    rarity: "rare",
    cost: 5,
    attack: 5,
    armor: 2,
    hp: 8,
    range: 1,
    movement: 1,
    initiative: 1,
    abilityText: "Мощный тяжелый танк.",
  },
  {
    id: "stug_iii",
    name: "StuG III",
    nation: "germany",
    class: "td",
    rarity: "uncommon",
    cost: 3,
    attack: 4,
    armor: 1,
    hp: 4,
    range: 1,
    movement: 1,
    initiative: 2,
    abilityText: "ПТ-САУ с хорошей дальностью.",
  },
  {
    id: "m4_sherman",
    name: "M4 Sherman",
    nation: "usa",
    class: "medium",
    rarity: "common",
    cost: 3,
    attack: 3,
    armor: 1,
    hp: 5,
    range: 1,
    movement: 1,
    initiative: 4,
    abilityText: "Маневренный средний танк.",
  },
  {
    id: "m5_stuart",
    name: "M5 Stuart",
    nation: "usa",
    class: "light",
    rarity: "common",
    cost: 1,
    attack: 1,
    armor: 0,
    hp: 3,
    range: 1,
    movement: 2,
    initiative: 5,
    abilityText: "Легкий танк: может двигаться на 2 клетки.",
  },
  {
    id: "churchill",
    name: "Churchill",
    nation: "uk",
    class: "heavy",
    rarity: "uncommon",
    cost: 4,
    attack: 2,
    armor: 3,
    hp: 8,
    range: 1,
    movement: 1,
    initiative: 1,
    abilityText: "Очень крепкая броня.",
  },
  {
    id: "marder_iii",
    name: "Marder III",
    nation: "germany",
    class: "td",
    rarity: "common",
    cost: 2,
    attack: 4,
    armor: 0,
    hp: 2,
    range: 1,
    movement: 1,
    initiative: 2,
    abilityText: "Высокий урон, слабая защита.",
  },
  {
    id: "wespe",
    name: "Wespe",
    nation: "germany",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 0,
    hp: 3,
    range: 99,
    movement: 1,
    initiative: 1,
    abilityText: "САУ: большая дальность.",
  },
  {
    id: "su_122",
    name: "SU-122",
    nation: "ussr",
    class: "spg",
    rarity: "uncommon",
    cost: 3,
    attack: 2,
    armor: 1,
    hp: 4,
    range: 99,
    movement: 1,
    initiative: 1,
    abilityText: "Советская САУ с дальностью 3.",
  },
];

export function getCard(cardId: string): TankCard {
  const card = cards.find((item) => item.id === cardId);

  if (!card) {
    throw new Error(`Card not found: ${cardId}`);
  }

  return card;
}